### ISSUE TITLE
Linux/ OSX support?

### ISSUE THREAD

**Issue by oscarbg** [Pierre-Terdiman/PEEL#1]
really Just asking how much difficult a port would be.. Also indirectly asking how hard is to obtain binaries for other platforms of all peel supported physics engines? For example seems havok via intel offers free win binaries only sdk..

**Comment by Pierre-Terdiman** [comment]
PEEL is built on top of my old engine, which is PC only. So it would be tedious to port to Linux/OSX. Nothing impossible but the whole UI for example, would need porting.

I don't have the time (or motivation) to do it myself. But I suppose this is what open-source is good for: people can just do it themselves :)

I don't think the Havok license allows one to re-distribute binaries, especially if it is for benchmarks purposes. So you have to go on their website, grab the SDK, and compile things yourself.
