### ISSUE TITLE
physx Gpu support

### ISSUE THREAD

**Issue by oscarbg** [Pierre-Terdiman/PEEL#2]
Hi,
Seems physxinfo was offered with physx gpu support in Peel in his testing years ago..
Why it has been removed?

**Comment by Pierre-Terdiman** [comment]
There was an old version of PEEL supporting GPU physics indeed, but:
1) it used an old GPU physics library which is obsolete by now. It is currently being replaced with a newer implementation.
2) We also have FLEX now, which is kind of better anyway.
3) None of these things have been officially released as libraries, so of course I am not allowed to just go ahead and do that myself :)

**Comment by Pierre-Terdiman** [comment]
There is some news here: PhysX 3.4 will be officially released "soon" and it now features built-in GPU rigid bodies. So, support for it in PEEL will probably be added next year, when PhysX 3.4 is released.

**Comment by oscarbg** [comment]
Thanks for the news.. have access already to Physx 3.4 gameworks branch.. One question is seeing slides of GDC CHina GRB presentation (https://developer.nvidia.com/sites/default/files/akamai/gameworks/events/cgdc16/GPU%20Rigid%20Body%20Simulation_cn.pdf)
I see slide 22 Arena demo (a demo shown associated with Siggraph paper about real time physics destruction some years ago)..
So is real time GPU physics destruction coming also in 3.4?
